# -*- ispell-dictionary: "spanish" -*-
#+SETUPFILE: ./course-es.org

#+TITLE: {{{unit09}}}

#+MATS: bib
#+begin_bibbox
- Wooldridge: ::  /Introducción a la Econometría/. Capítulo 10.
- Stock y Watson: ::  /Introducción a la Econometría/. Capítulo 14,
  secciones 14.6 a 14.8, y capítulo 15, secciones 15.1 a 15.3.
#+end_bibbox

* Modelos de regresión con series temporales


** Introducción

- Con series temporales es posible investigar las relaciones dinámicas
  entre variables.

- En primer lugar, examinaremos algunos modelos comúnmente utilizados.


** Modelos estáticos

- En un *modelo estático*, un cambio en una variable explicativa sólo
  tiene efectos en el periodo en que se produce y no tiene influencia
  en los periodos posteriores.

- Todas las variables del modelo se refieren al mismo periodo
  temporal:
  #+begin_export latex
  \[
    y_t = \alpha + \beta z_{t} + u_t,
  \]
  #+end_export
  donde $y_t$ es la variable dependiente, $z_t$ la variable
  explicativa, $\alpha$ y $\beta$ son parámetros desconocidos, $t = 1,
  2, \dots, T$ y $u_t$ es un término de error no observable tal que
  $\Exp(u_t | z_t) = 0$.


** Modelos de retardos distribuidos

- En un *modelo de retardos distribuidos* los cambios en las
  variables explicativas tienen efectos en más de un periodo.

- Estos modelos se caracterizan por incluir retardos de las variables
  explicativas:
  #+begin_export latex
  \[
    y_t = \alpha + \beta_0 z_{t} + \beta_1 z_{t-1} + \beta_2 z_{t-2} + \dots + \beta_L z_{t-L} + u_t,
  \]
  #+end_export
  donde $L$ es el número de retardos que aparecen en el modelo, y
  $\Exp(u_t | z_t, z_{t-1}, z_{t-2}, \dots) = 0$.


** Equilibrio dinámico

- Utilizaremos como ejemplo un modelo con dos retardos:
  #+begin_export latex
  \[
    y_t = \alpha + \beta_0 z_{t} + \beta_1 z_{t-1} + \beta_2 z_{t-2} + u_t,
  \]
  #+end_export

- En ausencia de perturbaciones, $u_t = 0$, en equilibrio dinámico las
  variables toman siempre el mismo valor: $y_t = y^*$ y $z_t = z^*$.

- Supongamos que, partiendo de un equilibrio dinámico, la variable $z$
  aumenta permanentemente en una unidad en el periodo 3. ¿Cómo se
  ajustarían las variables al nuevo equilibrio?


** Ajuste a un nuevo equilibrio

La tabla muestra como se ajustan las variable dependiente a un cambio
unitario permanente de $z$. En el nuevo equilibrio $z_t = z^* + 1$ e
$y_t = y^* + \beta_0 + \beta_1 + \beta_2$.


#+ATTR_LATEX: :align c@{\hspace{1cm}}l@{\hspace{1cm}}*{4}{c}@{\hspace{1cm}}l :booktabs t
| $t$      | $z_t$     | $\incr z_t$ | $\incr z_{t-1}$ | $\incr z_{t-2}$ | $\incr y_{t}$ | $y_t$                               |
|----------+-----------+-------------+-----------------+-----------------+---------------+-------------------------------------|
| $1$      | $z^*$     | $0$         | $0$             | $0$             | $0$           | $y^*$                               |
| $2$      | $z^*$     | $0$         | $0$             | $0$             | $0$           | $y^*$                               |
| $3$      | $z^* + 1$ | $1$         | $0$             | $0$             | $\beta_0$     | $y^* + \beta_0$                     |
| $4$      | $z^* + 1$ | $0$         | $1$             | $0$             | $\beta_1$     | $y^* + \beta_0 + \beta_1$           |
| $5$      | $z^* + 1$ | $0$         | $0$             | $1$             | $\beta_2$     | $y^* + \beta_0 + \beta_1 + \beta_2$ |
| $6$      | $z^* + 1$ | $0$         | $0$             | $0$             | $0$           | $y^* + \beta_0 + \beta_1 + \beta_2$ |
| $7$      | $z^* + 1$ | $0$         | $0$             | $0$             | $0$           | $y^* + \beta_0 + \beta_1 + \beta_2$ |
| $\vdots$ |           |             |                 |                 |               |                                     |


** Multiplicadores dinámicos

- El parámetro $\beta_0$ es el *multiplicador de impacto* o
  *multiplicador de corto plazo*. Es el efecto inmediato o
  contemporáneo de un cambio unitario de $z_t$ sobre $y_t$.

- Los parámetros $\beta_h$, $h = 0, 1, \dots$, son los
  *multiplicadores dinámicos* y miden el efecto de $z$ sobre $y$
  después de $h$ periodos:
  #+begin_export latex
  \[
    \iratio{y_t}{z_{t-h}} = \iratio{y_{t+h}}{z_{t}} = \beta_h.
  \]
  #+end_export


** Multiplicadores acumulativos

- Los *multiplicadores acumulativos*, $\delta_h$, suman los efectos
  que produce un cambio unitario de $z$ sobre la variable dependiente
  conforme pasa el tiempo:

  #+ATTR_LATEX: :align @{}cl@{} :booktabs t
  | Periodos transcurridos | Multiplicador acumulativo                |
  |------------------------+------------------------------------------|
  | $0$                    | $\delta_0 = \beta_0$                     |
  | $1$                    | $\delta_1 = \beta_0 + \beta_1$           |
  | $2$                    | $\delta_2 = \beta_0 + \beta_1 + \beta_2$ |
  | $\vdots$               | $\vdots$                                 |
  | $L$                    | $\delta_L = \sum_{i=0}^L \beta_i$        |

- En la última fila de la tabla aparece el *multiplicador de largo
  plazo*, $\delta_L$, que es la suma de todos los multiplicadores
  dinámicos.


** Modelos autorregresivos

- En un *modelo autorregresivo* las variables explicativas son
  retardos de la variable dependiente.

- Modelo autorregresivo de orden p, AR(p):
  #+begin_export latex
  \[
     y_t = \alpha + \rho_1 y_{t-1} + \rho_2 y_{t-2} + \dots +  \rho_p y_{t-p} + u_{t},
  \]
  #+end_export
  donde $\Exp(u_t | y_{t-1}, y_{t-2}, \dots) = 0$.


** Modelos ARDL

- Un *modelo autorregresivo con retardos distribuidos*,
  $\text{ARDL}(p, q)$, incluye como variables explicativas $p$
  retardos de $y$ y $q$ retardos de $z$:
  #+begin_export latex
  \[
    y_t =
    \alpha + \rho_1 y_{t-1} +
    \dots +
    \rho_p y_{t-p} +
    \beta_0 z_{t} +
    \beta_1 z_{t-1} +
    \dots +
    \beta_q z_{t-q} +
    u_{t},
  \]
  #+end_export
  donde $\Exp(u_t | z_t, y_{t-1}, z_{t-1}, y_{t-2}, z_{t-2}, \dots) = 0$.


* El modelo clásico de regresión con series temporales


** Introducción

- ¿Podemos usar MCO para estimar modelos de series temporales?

- ¿Qué tiene que cumplirse para que MCO tenga buenas propiedades
  exactas?



** Supuestos

Los supuestos del *modelo clásico de regresión lineal con series
temporales* son:

- *ST.1*: Linealidad en los parámetros.

- *ST.2*: Ausencia de colinealidad perfecta.

- *ST.3*: Media condicional nula.

- *ST.4*: Homoscedasticidad.

- *ST.5*: Ausencia de correlación serial.

- *ST.6*: Normalidad.


** Linealidad en los parámetros

*ST.1*: *Linealidad en los parámetros*.

El proceso estocástico $\{(y_t, x_{1t}, x_{2t}, \dots, x_{kt})\!: t = 1,
2, \dots, T\}$ sigue el modelo:
#+begin_export latex
\[
  y_t = \beta_0 + \beta_1 x_{1t} + \beta_1 x_{2t} + \dots + \beta_1 x_{kt} + u_t
\]
#+end_export
donde $\{u_t\!: t = 1, 2, \dots, T\}$ es una secuencia de perturbaciones
aleatorias no observables.



** Notación

- Nuestra especificación:
  #+begin_export latex
  \[
    y_t = \beta_0 + \beta_1 x_{1t} + \beta_1 x_{2t} + \dots + \beta_1 x_{kt} + u_t,
  \]
  #+end_export
  admite modelos dinámicos. Por ejemplo, obtenemos un modelo retardos
  distribuidos si definimos $x_{1t} = z_t, x_{2t} = z_{t-1}, \dots$

- $\bm{x_t} = (x_{1t}, x_{2t}, \dots, x_{kt})$: los valores que toman
  las explicativas en el periodo $t$.

- $\bm{X} = (\bm{x_1}, \bm{x_2}, \dots, \bm{x_T})$: los valores de
  todas las explicativas en todos los periodos de la muestra.



** Ausencia de colinealidad perfecta

*ST.2*: *Ausencia de colinealidad perfecta*.

En la muestra ninguna de las variables explicativas es constante ni
una combinación lineal perfecta de las otras explicativas.


** Media condicional nula

*ST.3*: *Media condicional nula*.

La media del término de error es $0$ condicional a los valores que
toman las explicativas en *todos* los periodos de tiempo :
#+begin_export latex
\[
  \Exp(u_t | \bm{X}) = 0,\quad t = 1, 2, \dots, T.
\]
#+end_export


** Exogeneidad estricta

*ST.3* implica que las variables explicativas son *estrictamente
exógenas*. El término de error $u_t$ debe estar incorrelacionado con
todas las explicativas en *todos* los periodos de tiempo:

- $\Exp(u_t | \bm{x_t}) = 0$: *exogeneidad contemporánea*.

- $\Exp(u_t | \bm{x_{t-1}}, \bm{x_{t-2}}, \dots, \bm{x_{1}}) =
  0$: incorrelación con valores pasados de $\bm{x_t}$.

- $\Exp(u_t | \bm{x_{t+1}}, \bm{x_{t+2}}, \dots, \bm{x_{T}}) = 0$:
  incorrelación con valores futuros de $\bm{x_t}$.



** Restricciones que impone la exogeneidad estricta

La exogeneidad estricta es incompatible con algunos casos importantes:

  + Efectos de *retroalimentación*: los valores que toma $y_t$ afectan
    a los valores futuros de las variables explicativas:
    $\bm{x_{t+1}}, \dots, \bm{x_{T}}$.

  + Modelos autorregresivos.


** Homoscedasticidad

*ST.4*: *Homoscedasticidad*.

Condicional a $\bm{X}$, la varianza de $u_t$ es la misma en todos los
periodos:
#+begin_export latex
\[
  \var(u_t | \bm{X}) = \sigma^2,\quad t = 1, 2, \dots, T.
\]
#+end_export


** Ausencia de correlación serial

*ST.5*: *Ausencia de correlación serial*.

Condicional a $\bm{X}$, las perturbaciones aleatorias de dos periodos
diferentes están incorrelacionadas:
#+begin_export latex
\[
  \corr(u_t, u_s | \bm{X}) = 0,\quad \text{para todo $t \neq s$.}
\]
#+end_export


** Normalidad

*ST.6*: *Normalidad*.

El término de error $u_t$ es independiente de $\bm{X}$ y se distribuye
independiente e idénticamente como $\Normal(0, \sigma^2)$.


** Propiedades de muestras finitas

Los supuestos del modelo clásico de regresión con series temporales
garantizan las siguientes propiedades del estimador de MCO:

- *Insesgadez*: si se cumplen *TS.1*, *TS.2* y *TS.3*.

- *Eficiencia*: si, además, se cumplen *TS.4* y *TS.5*. En este caso,
  se pueden usar las fórmulas de MCO de los errores típicos de
  $\hat{\beta_j}$.

- *Normalidad*: si, además, se cumple *TS.6*. Las fórmulas
  tradicionales de los contrastes $t$ y $F$ son válidas.


** Limitaciones del modelo clásico

- No es posible obtener estimaciones insesgadas de los parámetros de
  modelos que incluyan retardos de la variable dependiente.

- El estimador MCO tampoco tienen buenas propiedades exactas en
  presencia de efectos de retroalimentación.

- Algunos de los supuestos del modelo clásico son muy restrictivos:
  normalidad, exogeneidad estricta, ausencia de correlación serial,
  etc.


* Propiedades asintóticas de MCO con series temporales


** Introducción

¿Qué supuestos son necesarios para que el estimador MCO tenga buenas
propiedades asintóticas en modelos de regresión con series temporales?


** Supuestos

- *ST.1'*: Linealidad y dependencia débil.
- *ST.2'*: Ausencia de colinealidad perfecta.
- *ST.3'*: Exogeneidad (contemporánea).
- *ST.4'*: Homoscedasticidad.
- *ST.5'*: Ausencia de correlación serial.


** Linealidad y dependencia débil

*ST.1'*: *Linealidad y dependencia débil*.

El proceso estocástico $\{(y_t, x_{1t}, x_{2t}, \dots, x_{kt})\!: t =
1, 2, \dots, T\}$ es *estacionario* y *débilmente dependiente* sigue
el modelo:
#+begin_export latex
\[
  y_t = \beta_0 + \beta_1 x_{1t} + \beta_1 x_{2t} + \dots + \beta_1 x_{kt} + u_t
\]
#+end_export
donde $\{u_t\!: t = 1, 2, \dots, T\}$ es la secuencia de perturbaciones
aleatorias.


** Ausencia de colinealidad perfecta

*ST.2'*: *Ausencia de colinealidad perfecta*.

En la muestra ninguna de las variables explicativas es constante ni
una combinación lineal perfecta de las otras explicativas.



** Exogeneidad contemporánea

*ST.3'*: *Exogeneidad (contemporánea)*.

- Las variables explicativas $\bm{x}_t$ son *contemporáneamente exógenas*:
  #+begin_export latex
  \[
    \Exp(u_{t}|\bm{x}_{t}) = 0.
  \]
  #+end_export

- Este supuesto no se viola si se dan fenómenos de retroalimentación o
  si se incluyen retardos de la variable dependiente entre las
  explicativas.


** Homoscedasticidad y ausencia de autocorrelación

*ST.4'*: *Homoscedasticidad*.
#+begin_export latex
\[
  \var(u_t|\bm{x}_t) = \sigma^2.
\]
#+end_export
#+latex: \vspace*{2ex}

*ST.5'*: *Ausencia de correlación serial*.
#+begin_export latex
\[
  \corr(u_t, u_s | \bm{x}_t, \bm{x}_s) = 0,\quad \text{para todo $t \neq s$.}
\]
#+end_export


** Propiedades asintóticas

- *Consistencia*: si se cumplen *TS.1'* a *TS.3'*.

- *Normalidad asintótica*: si además se cumplen *TS.4'* y *TS.5'*.


** Conclusiones

- Con muestras de tamaño moderado o grande, bastan los supuestos
  *ST.1'* a *ST.5'* para garantizar buenas propiedades del estimador
  MCO.

- En particular, no es necesario realizar supuestos muy restrictivos
  como exogeneidad estricta o normalidad.

- Por otro lado, el supuesto *ST.1'* requiere estacionariedad y
  dependencia débil de la variable dependiente y de las variables
  explicativas.


* Inferencia asintótica


** Introducción

- Para estimar los errores típicos de $\hat{\beta}_j$ con las fórmulas
  tradicionales de MCO es necesario que se cumplan los supuestos
  *ST.4'* y *ST.5'*.

- Sin embargo, es frecuente encontrar correlación serial en el término
  de error.

- También es frecuente, especialmente en modelos financieros,
  la presencia de heteroscedasticidad.


** Inferencia robusta

- Las aportaciones de Newey y West, y de autores posteriores, muestran
  como pueden obtenerse estimaciones de $\var(\hat{\beta})$ que sólo
  requieren los supuestos *ST.1'*, *ST.2'* y *ST.3'* y que son válidas
  aun en presencia de correlación serial y heteroscedasticidad.

- Se suele usar el acrónimo *HAC* (/heteroskedasticity and
  autocorrelation consistent/) para referirse a esos errores típicos
  robustos.


** Contrastes $t$ robustos

La hipótesis nula $\beta_j = b$ puede contrastarse usando un cociente
$t$ robusto que utiliza la estimación MCO, $\hat{\beta}_j$, y un error
típico robusto a heteroscedasticidad y autocorrelación,
$\se_{\text{HAC}}(\bhat_j)$:
#+begin_export latex
\[
  t_{j} = \frac{\bhat_{j} - b}{\se_{\text{HAC}}(\bhat_{j})}.
\]
#+end_export


** Contrastes de hipótesis lineales

- En presencia de autocorrelación y heteroscedasticidad no es válido
  el estadístico $F$ que compara las $\SCR$ o los $\Rsq$ de los
  modelos restringido y no restringido. Tampoco existe una versión
  robusta de este contraste.

- Para contrastar restricciones lineales generales sobre los
  parámetros del modelo, utilizamos contrastes de Wald construidos con
  estimaciones de $\var(\hat{\bm\beta})$ robustas a
  heteroscedasticidad y autocorrelación.


** Estimación e inferencia robusta con MCO

- Se estiman por MCO los parámetros del modelo de regresión. MCO es
  consistente si se cumplen los supuestos *ST.1'*, *ST.2'* y *ST.3'*.

- Los contrastes de hipótesis se llevan a cabo utilizando una
  estimación de $\var(\hat{\bm\beta})$ robusta a heteroscedasticidad y
  autocorrelación.
